import Head from 'next/head';
import { PAGE_TITLE } from '../constants';

export default function HomePage() {
  return (
    <>
      <Head>
        <title>A La Carte | {PAGE_TITLE.MAIN}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
      </Head>
    </>
  );
}
