import Head from 'next/head';

export default function HomePage() {
  return (
    <>
      <Head>
        <title>A La Carte | 알라카르테</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
      </Head>
    </>
  );
}
